name: Hola Mundo

on: [push]

jobs:
  uno:
    runs-on: ubuntu-latest

    steps:
      - name: Mensaje
        run: echo "Hola Mundo isai"

      - name: Touch File
        run: |
          touch hola.txt
          ls -al

      - name: Set text
        run: |
          echo "Hola Mundo isai" >> hola.txt
          ls -al

      - name: Read File
        run: cat hola.txt

  dos:
    runs-on: ubuntu-latest
    needs: [uno]

    steps:
      - name: Directorio
        run: ls -al
